export interface TradeGoodTags {
  symbol: string;
  tags: Tags;
}

export enum Tags {
  ORES = 'ORES',
  METALLS = 'METALLS',
  MODULES = 'MODULES',
  ENGINES = 'ENGINES',
  REACTORS = 'REACTORS',
  BIO = 'BIO',
  PRECIOUS_MATERIALS = 'PRECIOUS MATERIALS',
  MINERALS_AND_RESOURCES = 'MINERALS AND RESOURCES',
  MANUFACTURED_GOODS = 'MANUFACTURED GOODS',
  CONSUMABLES = 'CONSUMABLES',
  LUXURY_AND_FASHION = 'LUXURY AND FASHION',
  SCIENTIFIC_AND_RESEARCH_EQUIPMENT = 'SCIENTIFIC AND RESEARCH EQUIPMENT',
  SPACE_TECHNOLOGY = 'SPACE TECHNOLOGY',
  MILITARY_AND_DEFENSE = 'MILITARY AND DEFENSE',
  EXPLORATION_AND_SURVEY_EQUIPMENT = 'EXPLORATION AND SURVEY EQUIPMENT',
  CULTURAL_AND_HISTORICAL_ITEMS = 'CULTURAL AND HISTORICAL ITEMS'
}