import { Tags, TradeGoodTags } from '@types';

type GOOD_SYMBOL_TO_TAG_TYPE = {
  [key: TradeGoodTags['symbol']]: TradeGoodTags['tags'];
};

export const GOOD_SYMBOL_TO_TAG: GOOD_SYMBOL_TO_TAG_TYPE[] = [
  {
    IRON_ORE: Tags.ORES,
    COPPER_ORE: Tags.ORES,
    ALUMINUM_ORE: Tags.ORES,
    SILVER_ORE: Tags.ORES,
    GOLD_ORE: Tags.ORES,
    PLATINUM_ORE: Tags.ORES,
    URANITE_ORE: Tags.ORES,
    MERITIUM_ORE: Tags.ORES,
  },

  {
    IRON: Tags.METALLS,
    COPPER: Tags.METALLS,
    ALUMINUM: Tags.METALLS,
    SILVER: Tags.METALLS,
    GOLD: Tags.METALLS,
    PLATINUM: Tags.METALLS,
  },

  {
    MODULE_MINERAL_PROCESSOR_I: Tags.MODULES,
    MODULE_CARGO_HOLD_I: Tags.MODULES,
    MODULE_CREW_QUARTERS_I: Tags.MODULES,
    MODULE_ENVOY_QUARTERS_I: Tags.MODULES,
    MODULE_PASSENGER_CABIN_I: Tags.MODULES,
    MODULE_MICRO_REFINERY_I: Tags.MODULES,
    MODULE_ORE_REFINERY_I: Tags.MODULES,
    MODULE_FUEL_REFINERY_I: Tags.MODULES,
    MODULE_SCIENCE_LAB_I: Tags.MODULES,
    MODULE_JUMP_DRIVE_I: Tags.MODULES,
    MODULE_JUMP_DRIVE_II: Tags.MODULES,
    MODULE_JUMP_DRIVE_III: Tags.MODULES,
    MODULE_WARP_DRIVE_I: Tags.MODULES,
    MODULE_WARP_DRIVE_II: Tags.MODULES,
    MODULE_WARP_DRIVE_III: Tags.MODULES,
    MODULE_SHIELD_GENERATOR_I: Tags.MODULES,
    MODULE_SHIELD_GENERATOR_II: Tags.MODULES,
  },

  {
    ENGINE_IMPULSE_DRIVE_I: Tags.ENGINES,
    ENGINE_ION_DRIVE_I: Tags.ENGINES,
    ENGINE_ION_DRIVE_II: Tags.ENGINES,
    ENGINE_HYPER_DRIVE_I: Tags.ENGINES,
  },

  {
    REACTOR_SOLAR_I: Tags.REACTORS,
    REACTOR_FUSION_I: Tags.REACTORS,
    REACTOR_FISSION_I: Tags.REACTORS,
    REACTOR_CHEMICAL_I: Tags.REACTORS,
    REACTOR_ANTIMATTER_I: Tags.REACTORS,
  },

  {
    NOVEL_LIFEFORMS: Tags.BIO,
    BOTANICAL_SPECIMENS: Tags.BIO,
    VIRAL_AGENTS: Tags.BIO,
    SUPERGRAINS: Tags.BIO,
    POLYNUCLEOTIDES: Tags.BIO,
    BIOCOMPOSITES: Tags.BIO,
    FERTILIZERS: Tags.BIO,
  },

  {
    PRECIOUS_STONES: Tags.PRECIOUS_MATERIALS,
    DIAMONDS: Tags.PRECIOUS_MATERIALS,
    URANITE: Tags.PRECIOUS_MATERIALS,
    MERITIUM: Tags.PRECIOUS_MATERIALS,
  },

  {
    QUARTZ_SAND: Tags.MINERALS_AND_RESOURCES,
    SILICON_CRYSTALS: Tags.MINERALS_AND_RESOURCES,
    AMMONIA_ICE: Tags.MINERALS_AND_RESOURCES,
    LIQUID_HYDROGEN: Tags.MINERALS_AND_RESOURCES,
    LIQUID_NITROGEN: Tags.MINERALS_AND_RESOURCES,
    ICE_WATER: Tags.MINERALS_AND_RESOURCES,
    HYDROCARBON: Tags.MINERALS_AND_RESOURCES,
    ANTIMATTER: Tags.MINERALS_AND_RESOURCES,
  },

  {
    ADVANCED_CIRCUITRY: Tags.MANUFACTURED_GOODS,
    MACHINERY: Tags.MANUFACTURED_GOODS,
    ELECTRONICS: Tags.MANUFACTURED_GOODS,
    SHIP_PLATING: Tags.MANUFACTURED_GOODS,
    EQUIPMENT: Tags.MANUFACTURED_GOODS,
    MICROPROCESSORS: Tags.MANUFACTURED_GOODS,
    PLASTICS: Tags.MANUFACTURED_GOODS,
    MICRO_FUSION_GENERATORS: Tags.MANUFACTURED_GOODS,
  },

  { FOOD: Tags.CONSUMABLES, 
    MEDICINE: Tags.CONSUMABLES, 
    DRUGS: Tags.CONSUMABLES, 
    FUEL: Tags.CONSUMABLES 
  },

  { JEWELRY: Tags.LUXURY_AND_FASHION, 
    FABRICS: Tags.LUXURY_AND_FASHION, 
    CLOTHING: Tags.LUXURY_AND_FASHION 
  },

  {
    LAB_INSTRUMENTS: Tags.SCIENTIFIC_AND_RESEARCH_EQUIPMENT,
    AI_MAINFRAMES: Tags.SCIENTIFIC_AND_RESEARCH_EQUIPMENT,
    GENE_THERAPEUTICS: Tags.SCIENTIFIC_AND_RESEARCH_EQUIPMENT,
    NEURAL_CHIPS: Tags.SCIENTIFIC_AND_RESEARCH_EQUIPMENT,
    MOOD_REGULATORS: Tags.SCIENTIFIC_AND_RESEARCH_EQUIPMENT,
  },

  {
    EXOTIC_MATTER: Tags.SPACE_TECHNOLOGY,
    QUANTUM_DRIVES: Tags.SPACE_TECHNOLOGY,
    ROBOTIC_DRONES: Tags.SPACE_TECHNOLOGY,
    CYBER_IMPLANTS: Tags.SPACE_TECHNOLOGY,
    HOLOGRAPHICS: Tags.SPACE_TECHNOLOGY,
    SHIP_SALVAGE: Tags.SPACE_TECHNOLOGY,
    RELIC_TECH: Tags.SPACE_TECHNOLOGY,
  },

  {
    MILITARY_EQUIPMENT: Tags.MILITARY_AND_DEFENSE,
    EXPLOSIVES: Tags.MILITARY_AND_DEFENSE,
    LASER_CANNON_I: Tags.MILITARY_AND_DEFENSE,
    MISSILE_LAUNCHER_I: Tags.MILITARY_AND_DEFENSE,
    TURRET_I: Tags.MILITARY_AND_DEFENSE,
    FIREARMS: Tags.MILITARY_AND_DEFENSE,
    ASSAULT_RIFLES: Tags.MILITARY_AND_DEFENSE,
    AMMUNITION: Tags.MILITARY_AND_DEFENSE,
    LASER_RIFLES: Tags.MILITARY_AND_DEFENSE,
  },

  {
    MOUNT_GAS_SIPHON_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_GAS_SIPHON_II: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_GAS_SIPHON_III: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SURVEYOR_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SURVEYOR_II: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SURVEYOR_III: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SENSOR_ARRAY_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SENSOR_ARRAY_II: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_SENSOR_ARRAY_III: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_MINING_LASER_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_MINING_LASER_II: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_MINING_LASER_III: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_LASER_CANNON_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_MISSILE_LAUNCHER_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
    MOUNT_TURRET_I: Tags.EXPLORATION_AND_SURVEY_EQUIPMENT,
  },

  { CULTURAL_ARTIFACTS: Tags.CULTURAL_AND_HISTORICAL_ITEMS },
];