import { TradeGoodSymbols, TradeGoodTags } from '@constants';

export const TRADE_GOODS_WITH_TAGS: {
  [tradeGoodSymbol in TradeGoodSymbols]: Array<TradeGoodTags>;
} = {
  [TradeGoodSymbols.LIQUID_HYDROGEN]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.LIQUID_NITROGEN]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.ADVANCED_CIRCUITRY]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.IRON]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.MERITIUM]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.COPPER]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.ALUMINUM]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.SILVER]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.GOLD]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.PLATINUM]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.URANITE]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.HYDROCARBON]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.ANTIMATTER]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.FABRICS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.ELECTRONICS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.SHIP_PLATING]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.MICROPROCESSORS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.PLASTICS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.POLYNUCLEOTIDES]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.BIOCOMPOSITES]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.GRAVITON_EMITTERS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.DIAMONDS]: [TradeGoodTags.COMPONENT],
  [TradeGoodSymbols.FUEL]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],

  [TradeGoodSymbols.QUARTZ_SAND]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.SILICON_CRYSTALS]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.AMMONIA_ICE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.ICE_WATER]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.EXOTIC_MATTER]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.IRON_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.COPPER_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.ALUMINUM_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.SILVER_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.GOLD_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.PLATINUM_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.URANITE_ORE]: [TradeGoodTags.RAW_MATERIAL],
  [TradeGoodSymbols.MERITIUM_ORE]: [TradeGoodTags.RAW_MATERIAL],

  [TradeGoodSymbols.FOOD]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.MEDICINE]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.DRUGS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.CLOTHING]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.CYBER_IMPLANTS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.GENE_THERAPEUTICS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.NEURAL_CHIPS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.MOOD_REGULATORS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.VIRAL_AGENTS]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.PRECIOUS_STONES]: [TradeGoodTags.CIVILIAN_SUPPLIES],
  [TradeGoodSymbols.JEWELRY]: [TradeGoodTags.CIVILIAN_SUPPLIES],

  [TradeGoodSymbols.FIREARMS]: [TradeGoodTags.WEAPONRY],
  [TradeGoodSymbols.ASSAULT_RIFLES]: [TradeGoodTags.WEAPONRY],
  [TradeGoodSymbols.MILITARY_EQUIPMENT]: [TradeGoodTags.WEAPONRY],
  [TradeGoodSymbols.EXPLOSIVES]: [TradeGoodTags.WEAPONRY],
  [TradeGoodSymbols.AMMUNITION]: [TradeGoodTags.WEAPONRY],
  [TradeGoodSymbols.LASER_RIFLES]: [TradeGoodTags.WEAPONRY],

  [TradeGoodSymbols.FERTILIZERS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.MACHINERY]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.LAB_INSTRUMENTS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.EQUIPMENT]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.NANOBOTS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.ROBOTIC_DRONES]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.AI_MAINFRAMES]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.QUANTUM_DRIVES]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.MICRO_FUSION_GENERATORS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.SUPERGRAINS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.SHIP_SALVAGE]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.RELIC_TECH]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.NOVEL_LIFEFORMS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.BOTANICAL_SPECIMENS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],
  [TradeGoodSymbols.CULTURAL_ARTIFACTS]: [TradeGoodTags.INDUSTRY_AND_SCIENCE],

  [TradeGoodSymbols.REACTOR_SOLAR_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.REACTOR_FUSION_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.REACTOR_FISSION_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.REACTOR_CHEMICAL_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.REACTOR_ANTIMATTER_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.ENGINE_IMPULSE_DRIVE_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.ENGINE_ION_DRIVE_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.ENGINE_ION_DRIVE_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.ENGINE_HYPER_DRIVE_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_MINERAL_PROCESSOR_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_CARGO_HOLD_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_CREW_QUARTERS_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_ENVOY_QUARTERS_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_PASSENGER_CABIN_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_MICRO_REFINERY_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_ORE_REFINERY_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_FUEL_REFINERY_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_SCIENCE_LAB_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_JUMP_DRIVE_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_JUMP_DRIVE_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_JUMP_DRIVE_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_WARP_DRIVE_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_WARP_DRIVE_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_WARP_DRIVE_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_SHIELD_GENERATOR_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MODULE_SHIELD_GENERATOR_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_GAS_SIPHON_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_GAS_SIPHON_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_GAS_SIPHON_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SURVEYOR_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SURVEYOR_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SURVEYOR_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SENSOR_ARRAY_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SENSOR_ARRAY_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_SENSOR_ARRAY_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_MINING_LASER_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_MINING_LASER_II]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_MINING_LASER_III]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_LASER_CANNON_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_MISSILE_LAUNCHER_I]: [TradeGoodTags.SHIP_MODULE],
  [TradeGoodSymbols.MOUNT_TURRET_I]: [TradeGoodTags.SHIP_MODULE],

  /**
   * Goods below don't have obvious tags for them.
   */
  [TradeGoodSymbols.HOLOGRAPHICS]: [],
};