/**
 * Trade goods separation in UI.
 */
export enum MarketSection {
  RAW_MATERIALS = 'RAW_MATERIALS',
  COMPONENTS = 'COMPONENTS',
  SHIP_MODULES = 'SHIP_MODULES',
  WEAPONRY = 'WEAPONRY',
  INDUSTRY_AND_SCIENCE = 'INDUSTRY_AND_SCIENCE',
  CIVILIAN_SUPPLIES = 'CIVILIAN_SUPPLIES',
}